dist: xenial

language: cpp
compiler: g++

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-9
            - cmake
            -
before_script:
  # https://stackoverflow.com/a/41916657
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-9
  - export CXX=/usr/bin/g++-9
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  - gcc-9 -v && g++-9 -v && cmake --version
  # grab opengml
  - git clone --branch v0.7.4 https://github.com/maiple/opengml
  # don't use prebuilt binaries.
  - rm datafiles/*.dll
  - rm datafiles/*.so*
  # build libs
  - cd lib && ./build.sh && cd -
  - cp lib/*.so datafiles/
  # Have to disable some features to get travis to build,
  # in particular must switch to 64-bit mode.
  - cd opengml && cmake . -DRELEASE=ON -DNETWORKING=OFF -DX64=ON && make && cd -
  - cp opengml/gig.so datafiles/gig.so
  # copy all .so files into main folder so they can be run.
  - cp datafiles/*.so* .
script:
  # run unit tests with dlls off.
  - ./opengml/ogm --version
  - ./opengml/ogm -DGME_ENABLED=false -DFMOD_ENABLED=false -DFS_ENABLED=false -DGameMusicEmu ./MegamixEngine.project.gmx --test 
  # check that tests passed.
  - cat "test.log"
  - grep -q success "test.log"
